export const TEXT = {
  appName: "DTBasket",
  appNameParts: { black: "DTBas", yellow: "ket" },
  tagline: "India's First Minute App",
  version: "v1.0.0",
  poweredBy: "Powered by divinetechs.",

  meta: {
    titleDefault: "DTBasket – Fresh Groceries Delivered Fast",
    titleTemplate: "%s | DTBasket",
    description: "Order fresh groceries, vegetables, fruits & daily essentials online. Fast delivery at best prices.",
  },

  topBar: {
    phone: "+91 98989 89898",
    email: "support@dtbasket.com",
    offer: "Free delivery on orders above ₹499",
    welcome: "Welcome to our store DTBasket!",
  },

  nav: {
    home: "Home",
    shop: "Shop",
    offers: "Offers",
    contact: "Contact",
    categories: "Categories",
    cart: "Cart",
    wishlist: "Wishlist",
    account: "Account",
    signIn: "Sign In",
    signOut: "Sign Out",
    allCategories: "All Categories",
    aboutUs: "About Us",
    myAccount: "My Account",
    orderTracking: "Order Tracking",
    followUs: "Follow Us:",
  },

  promo: {
    navBadge: "SALE",
    navText: "Get 30% Discount Now",
  },

  auth: {
    phoneStep: {
      headline: "Sign in to DTBasket",
      placeholder: "Enter 10-digit number",
    },
    loginSubtitle: "Sign in to your DTBasket account",
    registerSubtitle: "Join DTBasket for the best grocery experience",
    registerSuccess: "Account created! Welcome to DTBasket 🎉",
    signInTitle: "Sign In",
    rightPanel: {
      headline: "Order faster & \n easier everytime",
      subline: "with the DTBasket App",
      getItOn: "GET IT ON",
      googlePlay: "Google Play",
      downloadOn: "DOWNLOAD ON THE",
      appStore: "App Store",
    },
    otpSentTo: (phone: string) => `OTP sent to ${phone}`,
    loginSuccess: "Welcome back!",
    loginFailed: "Login failed. Please try again.",
    loginFailedCreds: "Login failed. Please check your credentials.",
    agreeTerms: "Please agree to the Terms & Privacy Policy",
    otpSendFailed: "Failed to send OTP. Please try again.",
    verifyFailed: "Verification failed. Please try again.",
    enterValidEmail: "Enter a valid email address",
    passwordMin: "Password must be at least 6 characters",
    otpResent: "OTP resent!",
    otpResendFailed: "Failed to resend OTP",
    sendingOtp: "Sending OTP...",
    continue: "Continue →",
    verifying: "Verifying...",
    verifyOtp: "Verify OTP",
    enterFullName: "Enter your full name",
    enterValidMobile: "Enter a valid mobile number",
    enterValidPhone: "Enter a valid 10-digit phone number",
    // Choose step
    continueWithPhone: "Continue with Phone",
    continueWithEmail: "Continue with Email",
    or: "OR",
    byContinuing: "By continuing, you agree to our",
    termsOfService: "Terms of Service",
    iAgreeTo: "I agree to the",
    // Phone step
    enterPhone: "Enter Phone Number",
    sendVerificationCode: "We'll send you a verification code",
    back: "Back",
    // OTP step
    otpVerification: "OTP Verification",
    otpSentTo2: "OTP has been sent to",
    resendIn: "Resend in",
    didntGetIt: "Didn't get it?",
    resendOtp: "Resend OTP",
    // Email step
    signInWithEmail: "Sign in with Email",
    emailAddress: "Email address",
    passwordPlaceholder: "Password (min 6 characters)",
    forgotPassword: "Forgot password?",
    noAccount: "Don't have an account?",
    registerNow: "Register now →",
    passwordsMismatch: "Passwords do not match",
    registrationFailed: "Registration failed. Please try again.",
    creatingAccount: "Creating Account...",
    createAccountBtn: "Create Account →",

    signInBtn: "Sign In →",
    signingIn: "Signing In...",
    signedOut: "Signed out",
    enterEmail: "Enter your email",
    enterPassword: "Enter your password",
    invalidCredentials: "Invalid email or password",

    // Form field labels / placeholders
    welcomeBack: "Welcome Back",
    createAccountHeadline: "Create Account",
    emailFieldPlaceholder: "Email Address",
    passwordFieldPlaceholder: "Password",
    fullNamePlaceholder: "Full Name *",
    emailRequiredPlaceholder: "Email Address *",
    mobileRequiredPlaceholder: "Mobile Number *",
    passwordMinPlaceholder: "Password (min 6 chars) *",
    confirmPasswordPlaceholder: "Confirm Password *",
    alreadyHaveAccount: "Already have an account?",
    signInLink: "Sign In",

    // Forgot password page
    forgotPasswordSubtitle: "Enter your email and we'll send you a reset link.",
    sendResetLink: "Send Reset Link",
    emailSentTitle: "Check your email",
    emailSentDesc: (email: string) => `We've sent a password reset link to ${email}`,
    tryDifferentEmail: "Try a different email",
    backToSignIn: "Back to Sign In",
  },

  home: {
    exploreCategories: "Explore Categories",
    seeAll: "See All →",
    featuredProducts: "Featured Products",
    newArrivals: "New Arrivals",
    bestSellers: "Best Sellers",
    topRated: "Top Rated",
  },

  features: [
    { icon: "🚀", title: "Express Delivery", desc: "Delivered in 30 minutes" },
    { icon: "🌿", title: "Fresh & Organic", desc: "100% quality guaranteed" },
    { icon: "💰", title: "Best Prices", desc: "Lowest prices guaranteed" },
    { icon: "🔄", title: "Easy Returns", desc: "Hassle-free returns" },
  ],

  search: {
    placeholder: "Search for products, categories",
    button: "Search",
    noResults: (q: string) => `No results for "${q}"`,
    viewAll: (q: string) => `View all results for "${q}"`,
    emptyHeading: "No products found",
    emptySubtext: "Try different keywords or browse our categories.",
    enterTerm: "Enter a search term to find products.",
    noResultsFor: "No results found for",
  },

  category: {
    noProducts: "No products found",
    noProductsSub: "Try a different category or search for items.",
    noCategories: "No categories found",
    breadcrumbHome: "Home",
    breadcrumbCategories: "Categories",
    allLabel: "All",
    productsCount: "products",
    trySearch: "Start shopping",
  },

  product: {
    add: "ADD",
    addToCart: "Add To Cart",
    addedToCart: "Added to cart!",
    outOfStock: "Out of Stock",
    inStock: "In Stock",
    soldOut: "Sold Out",
    soldOutShort: "Sold out",
    notify: "Notify",
    off: "OFF",
    fresh: "Fresh",
    lowStock: (n: number) => `Only ${n} left`,
    freeDelivery: "Free Delivery",
    freeDeliveryDesc: "on this item",
    reviews: "reviews",
    noReviews: "No reviews yet. Be the first to review!",
    wishlist: "Wishlist",
    wishlisted: "Wishlisted",
    addToWishlist: "Add to wishlist",
    removeFromWishlist: "Remove from wishlist",
    couponsOffers: "Coupons & Offers",
    viewAllCoupons: "View all coupons",
    hideCoupons: "Hide coupons",
    easyReturns: "Easy\nReturns",
    fastDelivery: "Fast\nDelivery",
    highlights: "Highlights",
    information: "Information",
    similarProducts: "Similar Products",
    deliveryIn: "Delivery in 4 mins",
    netQty: "Net Qty",
    onePack: "1 pack",
    // Highlight / Information labels
    labelBrand: "Brand",
    labelProductType: "Product Type",
    labelFlavour: "Flavour",
    labelKeyFeatures: "Key Features",
    labelSpiceLevel: "Spice Level",
    labelMaterialType: "Material Type Free",
    labelIngredients: "Ingredients",
    labelDietaryPref: "Dietary Preference",
    labelWeight: "Weight",
    labelUnit: "Unit",
    labelPackaging: "Packaging Type",
    labelStorage: "Storage Instruction",
    labelDisclaimer: "Disclaimer",
    labelCustomerCare: "Customer Care Details",
    labelSellerName: "Seller Name",
    labelSellerAddress: "Seller Address",
    labelSellerLicense: "Seller License No.",
    labelManufacturer: "Manufacturer & Marketer Name",
    labelManufacturerAddr: "Manufacturer & Marketer Address",
    labelCountry: "Country Of Origin",
    labelShelfLife: "Shelf Life",

  },

  carts: {
    title: "Cart",
    emptyTitle: "Your cart is empty",
    emptySubtitle: "Add items to start shopping",
    continueShopping: "Continue Shopping",
    subtotal: "Subtotal",
    deliveryFee: "Delivery Fee",
    freeDelivery: "FREE",
    total: "Total",
    orderSummary: "Order Summary",
    checkout: "Proceed to Checkout",
    viewCart: "View Cart",
    missedSomething: "Missed something?",
    addMoreItems: "+ Add More Items",
    addAddressToProceed: "Add Address to proceed",
    deliveringTo: "Delivering to",
    walletTitle: "Add Money to DTBasket Wallet",
    deliveryIn: "Delivery in 4 mins",
    viewAllCoupons: "View all coupons →",
    billSummary: "Bill summary",
    itemTotal: "Item Total",
    handlingFee: "Handling Fee",
    toPay: "To Pay",
    savingsTitle: "Savings on this order",
    discountMRP: "Discount on MRP",
    savingsHandling: "Savings on Handling fee",
    deliveryInstructions: "Delivery Instructions",
    deliveryPartnerTip: "Delivery Partner Tip",
    deliveryNotified: "Delivery partner will be notified",
    tipGoesTo: "This amount goes to your delivery partner",
    applyCoupons: "Apply Coupons",
    enterCouponCode: "Enter Coupon Code",
    availableCoupons: "Available Coupons",
    noCoupons: "No coupons available",
    useCode: "Use code:",
    apply: "APPLY",
    proceeding: "Processing…",
    proceedAddress: "Proceed with Selected Address",
    addNewAddress: "Add New Address",
    savedAddresses: "Saved Addresses",
    noAddresses: "No saved addresses",
    selectLocation: "Select Location",
    yourLocation: "Your location",
    payNow: (amt: number) => `Pay ₹${amt}`,
    saving: "Yay! You saved",
    onThisOrder: "on this order",
    addItemsWorth: "Add items worth",
    moreToApply: "more to apply",
    getExtra: "Get extra",
    off: "OFF",
    howItWorks: "How it works?",
    saveAddress: "Save Address",
    editAddress: "Edit Address",
    toGetFreeDelivery: "to get free delivery",
    fillRequired: "Fill required fields",
    selectAddressFirst: "Select an address first",
    clearAll: "Clear All",
    promoCode: "Promo Code",
    youSaved: "You saved",
    getExtraOff: "Get extra ₹50 OFF",
    validTill: "Valid till",
    fieldFullAddress: "Full Address *",
    fieldArea: "Area / Locality",
    fieldCity: "City *",
    fieldState: "State",
    fieldPincode: "Pincode *",
    invalidCoupon: "Invalid or unavailable coupon code",
    couponNotApplicable: "Coupon not applicable",
    addressHome: "Home",
    addressOffice: "Office",
    addressWork: "Work",
    addressOther: "Other",

    recentTransactions: "Recent Transactions",
    seeAll: "See All →",
    enterAmount: "Enter Amount",
    addBalance: "Add Balance",
    addMoney: "Add Money to DTBasket Wallet",
    placedOrder: "Placed Order",
    orderRefunded: "Order Refunded",
    addedToWallet: "Added to Wallet",
    easyPayments: "Easy & Fast\nPayments",
    instantRefunds: "Instant\nRefunds",
    exclusiveOffers: "Exclusive\nOffers",
  },

  checkout: {
    title: "Checkout",
    deliveryAddress: "Delivery Address",
    paymentMethod: "Payment Method",
    placeOrder: "Place Order",
    orderPlaced: "Order Placed!",
    orderPlacedDesc: "Your order has been placed successfully.",
    paymentCod: "Cash on Delivery",
    paymentOnline: "Online Payment",
    paymentWallet: "Wallet",
    orderPlacedSuccess: "Order placed successfully! 🎉",
    fillAddress: "Fill required address fields",
    selectAddress: "Select a delivery address",
    cartEmpty: "Your cart is empty",
    enterPromoCode: "Enter a promo code",
    deliveryLabel: "Delivery",
    available: "Available",
    newAddressHeadline: "New Address",
    addNew: "Add New",
    noSavedAddresses: "No saved addresses. Add one above.",
    placingOrder: "Placing Order...",
  },

  payment: {
    selectMethod: "Select Payment Method",
    cashOnDelivery: "Cash On Delivery",
    billTotal: "Bill Total",
    orderPayment: "Order Payment",
    gatewayNotConfigured: "Payment gateway not configured. Please try another method.",
  },

  orders: {
    itemsHeading: "Items",
    orderIdPrefix: "Order",
    deliveryAddress: "Delivery Address",
    itemsTotal: "Items Total",
    deliveryCharges: "Delivery Charges",
    totalPaid: "Total Paid",
    downloadInvoice: "Download Invoice",
    deliveryPartnerUnassigned: "Delivery partner not yet assigned",
    qty: "Qty",
    reorder: "Reorder",
    repeatOrder: "Repeat Order",
    reordering: "Adding…",
    reorderSuccess: "Items added to cart!",
    reorderFailed: "Failed to add some items. Please try again.",
    statusLabels: [
      { value: 0, label: "All Orders" },
      { value: 1, label: "Pending" },
      { value: 2, label: "Confirmed" },
      { value: 3, label: "Picking" },
      { value: 4, label: "Packed" },
      { value: 5, label: "Out for Delivery" },
      { value: 6, label: "Delivered" },
      { value: 7, label: "Cancelled" },
      { value: 8, label: "Rejected" },
    ],
  },

  wishlist: {
    title: "My Wishlist",
    emptyTitle: "Your wishlist is empty",
    emptySubtitle: "Save your favourite items here",
    signInPrompt: "Sign in to view and manage your wishlist",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    itemCount: (n: number) => `(${n} items)`,

  },

  account: {
    title: "My Account",
    profile: "Profile",
    orders: "Orders",
    addresses: "Addresses",
    notifications: "Notifications",
    transactions: "Transactions",
    wallet: "Wallet",
    walletCard: "Wallet & Gift Card",
    signOut: "Log Out",
    needHelp: "Need Help?",
    manageReferrals: "Manage Referrals",
    settings: "Settings",
    version: "v1.2.0",
    availableBalance: "Available Balance",
    addBalance: "Add Balance",
    myOrder: "My Order",
    loadMore: "↓ Load More",
    trackOrder: "Track Order",
    rateOrder: "Rate your order",
    startShopping: "Start Shopping",
    noOrders: "No orders yet",
    noOrdersSub: "Start shopping to see your orders here.",
    faqs: "FAQs",
    faqItems: [
      "Coupons & Offers",
      "General Inquiry",
      "Payment Related",
      "Feedback & Suggestions",
      "Order / Products Related",
    ],
    settingsItems: [
      { label: "Change Language", right: null },
      { label: "Dark Mode", right: "Light" },
      { label: "About Us", right: null },
      { label: "Share App", right: null },
      { label: "Legal and Privacy", right: null },
    ],
    deleteAccount: "Delete Account",
    deleteAccountWarn: "Deleting your account will remove all your orders, wallet amount and any active referral.",
    noSpam: "We promise not to spam you",
    popular: "POPULAR",
    noTransactions: "No transactions yet.",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    saving: "Saving…",
    addNewAddress: "Add New Address",
    savedAddresses: "Saved Addresses",
    noAddresses: "No saved addresses. Add one during checkout.",
    removeAddress: "Remove",
    signInToView: "Sign in to your account",
    signInSub: "Manage your orders, addresses, and more",
    referralDesc: "Refer friends and earn exciting rewards!",
    addressRemoved: "Address removed",
    orderRefunded: "Order Refunded",
    placedOrder: "Placed Order",
    viewOrders: "View Your Orders",
    ordersSignInSub: "Sign in to see your complete order history",
    placedAt: "Placed at",
    addressAdded: "Address added!",
    profileUpdated: "Profile updated!",
    howItWorks: "How it works?",
    addressUpdated: "Address Updated"
  },

  orderStatus: {
    0: "Order Pending",
    1: "Order Confirmed",
    2: "Order On the Way",
    3: "Order delivered",
    4: "Order cancelled",
  } as Record<number, string>,

  pagination: {
    previous: "← Previous",
    next: "Next →",
    loadMore: "Load More",
    loadingMore: "Loading more…",
  },

  common: {
    backToHome: "← Back to Home",
    seeAll: "See All →",
    noData: "No data found",
    loading: "Loading…",
    error: "Something went wrong",
    retry: "Try Again",
    startShopping: "Start Shopping",
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    submit: "Submit",
    continue: "Continue",
    back: "Back",
    apply: "Apply",
    remove: "Remove",
    add: "Add",
    confirm: "Confirm",
    discount: "Discount",
    state: "State",
    enterValidAmount: "Enter a valid amount",
    viewMore: "View more",
    viewLess: "View less",
    change: "Change",
  },

  footer: {
    description: "DTBasket is India's best food and grocery store. With over 200 handpicked products in the catalogue, you will find everything you are looking for.",
    tagline: "Fresh groceries delivered to your door. Quality products at the best prices.",
    contact: {
      heading: "Contact Us",
      phone: "798-4-798-190",
      whatsapp: "7984798190",
      email: "info@dtbasket.com",
      address: "DTBasket, Kudasan, Gandhinagar, Gujarat - 382421",
    },
    quickLinks: {
      heading: "Quick Links",
      links: [
        { label: "Home", href: "/", newTab: false },
        { label: "My Account", href: "/account", newTab: false },
      ],
    },
    policies: {
      heading: "Policies",
      links: [
        { label: "Shipping Policy", href: "/shipping-policy" },
        { label: "Terms and conditions", href: "/terms" },
        { label: "Refund Policy", href: "/refund-policy" },
      ],
    },
    copyright: `Copyright © ${new Date().getFullYear()} DTBasket All rights reserved.`,
    poweredBy: "Powered by divinetechs.",
  },

  support: {
    cashback: "Order on DTBasket and get Assured Cashback from CRED",
    customerCare: "In case of any issue, contact us E-mail address: support@dtbasket.com",
  },

  social: {
    facebook: "https://facebook.com/dtbasket",
    instagram: "https://instagram.com/dtbasket",
    twitter: "https://twitter.com/dtbasket",
    youtube: "https://youtube.com/dtbasket",
    linkedin: "https://linkedin.com/company/dtbasket",
  },

  appStore: {
    googlePlay: "https://play.google.com/store/apps/details?id=com.divinetechs.dtbasket",
    appStore: "https://www.apple.com/in/app-store/",
  },

  notFound: {
    title: "Page Not Found",
    message: "The page you're looking for doesn't exist.",
    cta: "Go Home",
  },
  error: {
    title: "Something went wrong",
    message: "An unexpected error occurred. Please try again.",
    cta: "Try Again",
  },
  cart: {
    title: "Cart",
    emptyCart: "Your cart is empty",
    continueShopping: "Continue Shopping",

    addItemsWarning: "Add items worth ₹{amount} more to apply",

    coupon: {
      apply: "Apply",
      viewAll: "View all coupons →",
      applied: "applied! You saved ₹{amount}",
    },

    delivery: {
      time: "Delivery in 4 mins",
    },

    bill: {
      title: "Bill summary",
      itemTotal: "Item Total",
      handlingFee: "Handling Fee",
      deliveryFee: "Delivery Fee",
      toPay: "To Pay",
    },

    savings: {
      title: "Savings on this order",
      mrpDiscount: "Discount on MRP",
      handlingSavings: "Savings on Handling fee",
    },

    instructions: {
      title: "Delivery Instructions",
      subtitle: "Delivery partner will be notified",
      placeholder: "Add delivery instructions…",
    },

    tip: {
      title: "Delivery Partner Tip",
      subtitle: "This amount goes to your delivery partner",
    },

    address: {
      addToProceed: "Add Address to proceed",
      payNow: "Pay ₹{amount}",
    }
  }
} as const;

